
<style>
    table.seyrettemplatetable td {
        padding:0;
    }
    div#cattopleft {
        background-image:url("/img/cattopleft.png");
        height:14px;
        width:14px;
    }
    td, tr, p, div {
        background-color:transparent;
        color:Black;
        font-family:Verdana,ARIAL,HELVETICA,SANS-SERIF;
        font-size:12px;
    }
    div#cattopmid {
        background-image:url("/img/cattopmid.png");
        height:14px;
    }
    div#catbotmid {
        background-image:url("/img/catbotmid.png");
        height:14px;
    }
    div#catbotright {
        background-image:url("/img/catbotright.png");
        height:14px;
        width:14px;
    }
    div#cattopright {
        background-image:url("/img/cattopright.png");
        height:14px;
        width:14px;
    }
    table.seyrettemplatetable td {
        padding:0;
    }
    .catright {
        background-image:url("/img/catright.png");
    }
    .catleft {
        background-image:url("/img/catleft.png");
    }

    div#catbotleft {
        background-image:url("/img/catbotleft.png");
        height:14px;
        width:14px;
    }
</style>
<center>
    <table width='50%'><tr><td style='padding-top:10px;'>

                <div class="videolistdivintabs">
                    <table cellspacing="0" cellpadding="0" border="0" width="20%">
                        <tr>
                            <td width="14px"><div id="cattopleft">&nbsp;</div></td>
                            <td><div id="cattopmid">&nbsp;</div></td>
                            <td width="14px"><div id="cattopright">&nbsp;</div></td>
                        </tr>
                        <tr>
                            <td class="catleft">&nbsp;</td>
                            <td>
                                <table cellpadding="3" border="0" width="10%">
                                    <tr>
                                        <td width="1%" valign="top" rowspan="2">
                                            <a href='/index/weddingvideo/'><img border=0 class="videothumbnailinlists" src="/img/homepage.jpg" width='200' height='190'>
                                                <br>
                                                <center><b><font color='#FFFFFF'>Свадьбы</font></b></center>
                                        </td>
                                    </tr>

                                </table>
                            </td>
                            <td class="catright">&nbsp;</td>
                        </tr>
                        <tr>
                            <td width="14px"><div id="catbotleft">&nbsp;</div></td>
                            <td><div id="catbotmid"></div></td>
                            <td width="14px"><div id="catbotright">&nbsp;</div></td>
                        </tr>
                    </table>
                </div>
            </td><td style='padding-top:10px;padding-right:60px;padding-left:60px'>
                <div class="videolistdivintabs">
                    <table cellspacing="0" cellpadding="0" border="0" width="20%">
                        <tr>
                            <td width="14px"><div id="cattopleft">&nbsp;</div></td>
                            <td><div id="cattopmid">&nbsp;</div></td>
                            <td width="14px"><div id="cattopright">&nbsp;</div></td>
                        </tr>
                        <tr>
                            <td class="catleft">&nbsp;</td>
                            <td>
                                <table cellpadding="3" border="0" width="10%">
                                    <tr>
                                        <td width="1%" valign="top" rowspan="2">
                                            <a href='/index/lovestoryvideo/'><img border=0 class="videothumbnailinlists" src="/img/waves.jpg" width='200' height='190'></a>
                                            <br>
                                            <center><b><font color='#FFFFFF'>Love story</font></b></center>
                                        </td>
                                    </tr>
                                </table>
                            </td>
                            <td class="catright">&nbsp;</td>
                        </tr>
                        <tr>
                            <td width="14px"><div id="catbotleft">&nbsp;</div></td>
                            <td><div id="catbotmid"></div></td>
                            <td width="14px"><div id="catbotright">&nbsp;</div></td>
                        </tr>
                    </table>
                </div>
            </td>
            <td style="padding-top:10px;">
                <div class="videolistdivintabs">
                    <table cellspacing="0" cellpadding="0" border="0" width="20%">
                        <tr>
                            <td width="14px"><div id="cattopleft">&nbsp;</div></td>
                            <td><div id="cattopmid">&nbsp;</div></td>
                            <td width="14px"><div id="cattopright">&nbsp;</div></td>
                        </tr>
                        <tr>
                            <td class="catleft">&nbsp;</td>
                            <td>
                                <table cellpadding="3" border="0" width="10%">
                                    <tr>
                                        <td width="1%" valign="top" rowspan="2">
                                            <a href='/index/childrenvideo/'><img border=0 class="videothumbnailinlists" src="/img/ch.jpg" width='200' height='190'></a>
                                            <br>
                                            <center><b><font color='#FFFFFF'>Детское</font></b></center>
                                        </td>
                                    </tr>

                                </table>
                            </td>
                            <td class="catright">&nbsp;</td>
                        </tr>
                        <tr>
                            <td width="14px"><div id="catbotleft">&nbsp;</div></td>
                            <td><div id="catbotmid"></div></td>
                            <td width="14px"><div id="catbotright">&nbsp;</div></td>
                        </tr>
                    </table>
                </div>
            </td>
        </tr>
        <tr>


            <td style="padding-top:10px;" colspan=3 align='center'>

                <table><tr><td style="padding-right:100px">

                            <div class="videolistdivintabs">
                                <table cellspacing="0" cellpadding="0" border="0" width="20%">
                                    <tr>
                                        <td width="14px"><div id="cattopleft">&nbsp;</div></td>
                                        <td><div id="cattopmid">&nbsp;</div></td>
                                        <td width="14px"><div id="cattopright">&nbsp;</div></td>
                                    </tr>
                                    <tr>
                                        <td class="catleft">&nbsp;</td>
                                        <td>
                                            <table cellpadding="3" border="0" width="10%">
                                                <tr>
                                                    <td width="1%" valign="top" rowspan="2">
                                                        <a href='/index/finalsvideo'><img border=0 class="videothumbnailinlists" src="/img/fin.jpg" width='200' height='190'></a>
                                                        <br>
                                                        <center><b><font color='#FFFFFF'>Выпускные вечера</font></b></center>
                                                    </td>
                                                </tr>

                                            </table>
                                        </td>
                                        <td class="catright">&nbsp;</td>
                                    </tr>
                                    <tr>
                                        <td width="14px"><div id="catbotleft">&nbsp;</div></td>
                                        <td><div id="catbotmid"></div></td>
                                        <td width="14px"><div id="catbotright">&nbsp;</div></td>
                                    </tr>
                                </table>
                            </div>

                        </td>
                        <td>


                            <div class="videolistdivintabs">
                                <table cellspacing="0" cellpadding="0" border="0" width="20%">
                                    <tr>
                                        <td width="14px"><div id="cattopleft">&nbsp;</div></td>
                                        <td><div id="cattopmid">&nbsp;</div></td>
                                        <td width="14px"><div id="cattopright">&nbsp;</div></td>
                                    </tr>
                                    <tr>
                                        <td class="catleft">&nbsp;</td>
                                        <td>
                                            <table cellpadding="3" border="0" width="10%">
                                                <tr>
                                                    <td width="1%" valign="top" rowspan="2">
                                                        <a href='/index/othervideo/'><img border=0 class="videothumbnailinlists" src="/img/ses.jpg" width='200' height='190'></a>
                                                        <br>
                                                        <center><b><font color='#FFFFFF'>Разное</font></b></center>
                                                    </td>
                                                </tr>

                                            </table>
                                        </td>
                                        <td class="catright">&nbsp;</td>
                                    </tr>
                                    <tr>
                                        <td width="14px"><div id="catbotleft">&nbsp;</div></td>
                                        <td><div id="catbotmid"></div></td>
                                        <td width="14px"><div id="catbotright">&nbsp;</div></td>
                                    </tr>
                                </table>
                            </div>



                        </td>

                    </tr></table>



            </td>


        </tr>
    </table>
</center>


