
<br>
<?php print($this->navigation); ?>
<br><br>

<div id="gallery" style="display:none;">

            <?php
            $n = 0;

            foreach($this->list_photo as $key=>$val ){


                ?>

                <a href="<?php echo $this->url?>">
                <img alt=""
                     src="<?php echo $val['link'];?>"
                     data-image="/index/resize?file=<?php echo ltrim($val['link'], '/');?>"
                     data-description=""
                     style="display:none">
                </a>

            <?php } ?>

</div>


