<?php require_once("include/header.php"); ?>
  <style>
  table.seyrettemplatetable td {
padding:0;
}
   div#cattopleft {
background-image:url("<?php echo $this->domen;?>/img/cattopleft.png");
height:14px;
width:14px;
}
td, tr, p, div {
background-color:transparent;
color:Black;
font-family:Verdana,ARIAL,HELVETICA,SANS-SERIF;
font-size:12px;
}
div#cattopmid {
background-image:url("<?php echo $this->domen;?>/img/cattopmid.png");
height:14px;
}
div#catbotmid {
background-image:url("<?php echo $this->domen;?>/img/catbotmid.png");
height:14px;
}
div#catbotright {
background-image:url("<?php echo $this->domen;?>/img/catbotright.png");
height:14px;
width:14px;
}
div#cattopright {
background-image:url("<?php echo $this->domen;?>/img/cattopright.png");
height:14px;
width:14px;
}
table.seyrettemplatetable td {
padding:0;
}
.catright {
background-image:url("<?php echo $this->domen;?>/img/catright.png");
}
.catleft {
  background-image:url("<?php echo $this->domen;?>/img/catleft.png");
}

div#catbotleft {
background-image:url("<?php echo $this->domen;?>/img/catbotleft.png");
height:14px;
width:14px;
}
</style><br>

<br> 
<center>
<table width='50%'><tr><td style='padding-top:10px;'>

<div class="videolistdivintabs">
<table cellspacing="0" cellpadding="0" border="0" width="20%">
<tr>
<td width="14px"><div id="cattopleft">&nbsp;</div></td>
<td><div id="cattopmid">&nbsp;</div></td>
<td width="14px"><div id="cattopright">&nbsp;</div></td>
</tr>
<tr>
 <td class="catleft">&nbsp;</td>
 <td>
 <table cellpadding="3" border="0" width="10%">
 <tr>
  <td width="1%" valign="top" rowspan="2">
   <a href='<?php echo $this->domen;?>/photo/wedding/'><img border=0  class="videothumbnailinlists" src="<?php echo $this->domen;?>/img/wedd.jpg" width='200' height='190'>
   <br>
    <center><b><font color='#FFFFFF'>Свадьбы</font></b></center>
  </td>
 </tr>
 
</table>
</td>
<td class="catright">&nbsp;</td>
</tr>
<tr>
<td width="14px"><div id="catbotleft">&nbsp;</div></td>
<td><div id="catbotmid"></div></td>
<td width="14px"><div id="catbotright">&nbsp;</div></td>
</tr>
</table>
</div>
</td><td style='padding-top:10px;padding-right:60px;padding-left:60px'>
    <div class="videolistdivintabs">
<table cellspacing="0" cellpadding="0" border="0" width="20%">
<tr>
<td width="14px"><div id="cattopleft">&nbsp;</div></td>
<td><div id="cattopmid">&nbsp;</div></td>
<td width="14px"><div id="cattopright">&nbsp;</div></td>
</tr>
<tr>
 <td class="catleft">&nbsp;</td>
 <td>
 <table cellpadding="3" border="0" width="10%">
 <tr>
  <td width="1%" valign="top" rowspan="2">
   <a href='<?php echo $this->domen;?>/photo/lovestory/'><img border=0 class="videothumbnailinlists" src="<?php echo $this->domen;?>/img/waves2.jpg" width='200' height='190'></a>
    <br>
    <center><b><font color='#FFFFFF'>Love story</font></b></center>
  </td>
</tr>
</table>
</td>
<td class="catright">&nbsp;</td>
</tr>
<tr>
<td width="14px"><div id="catbotleft">&nbsp;</div></td>
<td><div id="catbotmid"></div></td>
<td width="14px"><div id="catbotright">&nbsp;</div></td>
</tr>
</table>
</div>
</td>
<td style="padding-top:10px;">
    <div class="videolistdivintabs">
<table cellspacing="0" cellpadding="0" border="0" width="20%">
<tr>
<td width="14px"><div id="cattopleft">&nbsp;</div></td>
<td><div id="cattopmid">&nbsp;</div></td>
<td width="14px"><div id="cattopright">&nbsp;</div></td>
</tr>
<tr>
 <td class="catleft">&nbsp;</td>
 <td>
 <table cellpadding="3" border="0" width="10%">
 <tr>
  <td width="1%" valign="top" rowspan="2">
   <a href='<?php echo $this->domen;?>/photo/children/'><img border=0 class="videothumbnailinlists" src="<?php echo $this->domen;?>/img/ch_photo.jpg" width='200' height='190'></a>
   <br>
    <center><b><font color='#FFFFFF'>Детское</font></b></center>
  </td>
 </tr>
 
</table>
</td>
<td class="catright">&nbsp;</td>
</tr>
<tr>
<td width="14px"><div id="catbotleft">&nbsp;</div></td>
<td><div id="catbotmid"></div></td>
<td width="14px"><div id="catbotright">&nbsp;</div></td>
</tr>
</table>
</div>
</td>
</tr>
<tr>
    
    
<td style="padding-top:10px;" colspan=3 align='center'>

<table><tr><td style="padding-right:100px">    
    
<div class="videolistdivintabs">
<table cellspacing="0" cellpadding="0" border="0" width="20%">
<tr>
<td width="14px"><div id="cattopleft">&nbsp;</div></td>
<td><div id="cattopmid">&nbsp;</div></td>
<td width="14px"><div id="cattopright">&nbsp;</div></td>
</tr>
<tr>
 <td class="catleft">&nbsp;</td>
 <td>
 <table cellpadding="3" border="0" width="10%">
 <tr>
  <td width="1%" valign="top" rowspan="2">
   <a href='<?php echo $this->domen;?>/photo/finals'><img border=0 class="videothumbnailinlists" src="<?php echo $this->domen;?>/img/final_photo.jpg" width='200' height='190'></a>
   <br>
    <center><b><font color='#FFFFFF'>Выпускные альбомы</font></b></center>
  </td>
 </tr>
 
</table>
</td>
<td class="catright">&nbsp;</td>
</tr>
<tr>
<td width="14px"><div id="catbotleft">&nbsp;</div></td>
<td><div id="catbotmid"></div></td>
<td width="14px"><div id="catbotright">&nbsp;</div></td>
</tr>
</table>
</div>

</td>
<td>
     
     
 <div class="videolistdivintabs">
<table cellspacing="0" cellpadding="0" border="0" width="20%">
<tr>
<td width="14px"><div id="cattopleft">&nbsp;</div></td>
<td><div id="cattopmid">&nbsp;</div></td>
<td width="14px"><div id="cattopright">&nbsp;</div></td>
</tr>
<tr>
 <td class="catleft">&nbsp;</td>
 <td>
 <table cellpadding="3" border="0" width="10%">
 <tr>
  <td width="1%" valign="top" rowspan="2">
   <a href='<?php echo $this->domen;?>/photo/other/'><img border=0 class="videothumbnailinlists" src="<?php echo $this->domen;?>/img/ses.jpg" width='200' height='190'></a>
   <br>
    <center><b><font color='#FFFFFF'>Разное</font></b></center>
  </td>
 </tr>
 
</table>
</td>
<td class="catright">&nbsp;</td>
</tr>
<tr>
<td width="14px"><div id="catbotleft">&nbsp;</div></td>
<td><div id="catbotmid"></div></td>
<td width="14px"><div id="catbotright">&nbsp;</div></td>
</tr>
</table>
</div>    
     
     
     
</td>    

</tr></table>



</td>


</tr>    
</table>
  </center>
<?php require_once("include/footer.php"); ?>
 
