adas
<br>
<?php print($this->navigation); ?>
<br><br>

<div id="gallery" style="display:none;">

    <?php
    $n = 0;

    foreach($this->list_photo as $key=>$val ){


        $pos = strripos( $val['link'], "/");
        $name = trim( substr($val['link'], $pos + 1, strlen($val['link']) - $pos) );

        ?>

        <a href="<?php echo $this->url?>">
            <img alt=""
                 src="/index/resize?file=img/other/<?php echo $name;?>&max_size=250"
                 data-image="<?php echo $val['link'];?>"
                 data-description=""
                 style="display:none">
        </a>

    <?php } ?>

</div>


