<meta content="text/html; charset=utf8" http-equiv="Content-Type" />
<center>
 <table><tr><td>Логин:</td>
 <form name='fAuth' method='POST' action="/admin/auth">
  
 <td>  <input type='text' name='tLogin' value=''></td></tr><tr>
<td>Пароль</td><td>
   <input type='password' name='tPass' value=''></td></tr><tr>
   <td align='center' colspan=2><input type="submit" value='Войти' name='sSubmit'><td>

 </form>
 </div>
</center>
