<?php echo $this->doctype() ?>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <title>victoria-k.dp.ua</title>
    <meta name="title" content="Главная">
    <meta name="author" content="Олег Кривко">
    <meta name="description" content="Видеосъемка  клип Днепропетровск Профессиональная фотосъемка Студия Виктория-К праздники видеограф портфолио  Love Story ">
    <meta name="keywords" content="Видеосъемка, клип, Днепропетровск, Профессиональная фотосъемка, Студия Виктория-К, праздники, видеограф, портфолио, лавстори, Love Story, Кривко Олег, Татьяна, тамада, музыка, дискотека, обслужевание торжеств, банкеты, корпоративы, свадьба, видео, фото,фотограф, фотография, фотосессия, съемка свадеб, фулшд, Full HD, DVD, ролик, фильм, мероприятие, детские праздники, новый год, утренники, выпускные вечера, портрет, репортаж, загс, прогулка, роспись, видеокамера, фотокамера, невеста, жених,  Oleg Krivko,  українське весілля, видеосъемка первого танца, свадьба в Днепропетровске, Весільна відеозйомка,видеосъемка истории знакомства, видео знакомства, українське весілля, видеооператор на свадьбу">
    <meta name="Generator" content="музыка дискотека обслужевание торжеств, банкеты  корпоративы, свадьба видео фото фотограф, фотография  фотосессия, съемка свадеб фулшд Full HD  DVD ролик фильм мероприятие детские праздники новый год утренники выпускные вечера портрет репортаж загс прогулка роспись видеокамера фотокамера невеста жених  Oleg Krivko
">
    <meta name="robots" content="">
    <link rel="stylesheet" type="text/css" href="<?=$this->domen;?>/css/css.css">
    <script src="<?=$this->domen;?>/js/lightgallery/lightgallery.js" type="text/javascript"></script>
    <script src="<?=$this->domen;?>/js/lightgallery/lang/ru_utf8.js" type="text/javascript"></script>
    <link href="<?=$this->domen;?>/js/lightgallery/skins/default/style.css" type="text/css" media="screen" rel="stylesheet">
    <link rel="icon" type="image/png" href="<?=$this->domen;?>/img/title.jpg">

    <link rel="stylesheet" type="text/css" href="<?=$this->domen;?>/yui2/fonts/fonts-min.css">
    <link rel="stylesheet" type="text/css" href="<?=$this->domen;?>/yui2/container/assets/skins/sam/container.css">
    <script type="text/javascript" src="<?=$this->domen;?>/yui2/yahoo-dom-event/yahoo-dom-event.js"></script>

    <script type="text/javascript" src="<?=$this->domen;?>/yui2/connection/connection-min.js"></script>
    <script type="text/javascript" src="<?=$this->domen;?>/yui2/animation/animation-min.js"></script>
    <script type="text/javascript" src="<?=$this->domen;?>/yui2/dragdrop/dragdrop-min.js"></script>
    <script type="text/javascript" src="<?=$this->domen;?>/yui2/container/container-min.js"></script>
    <script type="text/javascript">

        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-8802239-6']);
        _gaq.push(['_trackPageview']);

        (function() {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();

    </script>

    <style>
        .zoom{
            position:absolute;
            left:0px;
            top:0px;
            z-index:10;
            width:300;
        }
    </style>
</head>

<body onload='lightgallery.init();' class="yui-skin-sam">
<a name="top" id="top"></a>
<table border="0" align="center" width="750" cellspacing="2" cellpadding="3">
    <tr>
        <td>
            <table border="0" width="100%" cellspacing="0" cellpadding="0">
                <tr height="20">
                    <td valign="center" align="left" background="<?=$this->domen;?>/img/top_bar_back_gray.gif">
                    </td>
                    <td valign="center" align="right" background="<?=$this->domen;?>/img/top_bar_back_gray.gif" style='padding-right:10px;'>
                        <a href="<?=$this->domen;?>"><font color="#ffffff">victoria-k.dp.ua</font></a>
                    </td>
                </tr>
            </table>
            <table border="0" width="100%" cellspacing="0" cellpadding="0">
                <tr>
                    <td>
                        <a href='/'>
                            <img border=0  width="900px" height="230px" src="<?=$this->domen;?>/img/logo.jpg">
                        </a>
                    </td>
                </tr>
            </table>
            <table border="0" width="100%" cellspacing="0" cellpadding="0">
                <tr height="30">
                    <td valign="center" align="left" background="/img/menu_bar_back_gray.gif">
                        <table width="100%" border="0" cellpadding="0" cellspacing="1"><tr>
                                <td nowrap="nowrap">
                                    <?php require_once 'include/menu.php'; ?>
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </table>
            <table border="0" width="100%"  cellspacing="0" cellpadding="0" >
                <tr  height="450" style="">
                    <td valign="top" bgcolor="#bgcolor">
                        <div align='left'>
                            <font color='#FFFFFF'><strong><?=$this->title;?></strong></font>
                        </div>
                        <table  width="100%">
                            <tr>
                                <td width="885px" valign='top' style='padding-right:0px;'><font color='#FFFFFF'>

<?php echo $this->layout()->content ?>

                                    </font>
                                </td>
                            </tr>
                        </table>

                        <span class="article_seperator">&nbsp;</span>
                    </td>
                </tr>
            </table>
            <div>
                <img src="<?=$this->domen;?>/img/footer.jpg" width="900px">
            </div>
            <table border="0" width="100%" cellspacing="0" cellpadding="0">
                <tr height="20">
                    <td valign="center" style='padding-right:10px;' align="right" background="<?=$this->domen;?>/img/top_bar_back_gray.gif" >
                        <a href="<?=$this->domen;?>"><font color="#ffffff">victoria-k.dp.ua</font></a></td>
                </tr>
            </table>
        </td>
    </tr>
</table>
</body>
</html>
