<html>
<header>    
 <meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />
</header>
<body>
<?php include("time.phtml"); ?>
<table>
  <tr>
   <td><a href='<?php echo $this->domen;?>/admin/?type=main'><b><font color=<?php echo ($this->action =="main")?"#FF0000":"#000000";?> >Главная</font></b></a></td>
   <td><a href='<?php echo $this->domen;?>/admin/?type=about'><b><font color=<?php echo ($this->action =="about")?"#FF0000":"#000000";?> >О нас</font></b></a></td>
   <td><a href='<?php echo $this->domen;?>/admin/?type=uslugi'><b><font color=<?php echo ($this->action =="uslugi")?"#FF0000":"#000000";?> >Услуги</font</b></a></td>
   <td><a href='<?php echo $this->domen;?>/admin/?type=price'><b><font color=<?php echo ($this->action =="price")?"#FF0000":"#000000";?> >Цены</font></b></a></td>
   <td><a href='<?php echo $this->domen;?>/admin/?type=contacts'><b><font color=<?php echo ($this->action =="contacts")?"#FF0000":"#000000";?> >Контакты</font</b></a></td>
   <td><a href='<?php echo $this->domen;?>/admin/?type=more'><b><font color=<?php echo ($this->action =="more")?"#FF0000":"#000000";?> >Отзывы</font></b></a></td>
   <td><a href='<?php echo $this->domen;?>/admin/?type=photo'><b><font color=<?php echo ($this->action =="photo")?"#FF0000":"#000000";?> >Фото</font></b></a></td>
   <td><a href='<?php echo $this->domen;?>/admin/exit/'><b><font color=#000000>Выход</b></font</a></td>
  </tr>  
</table>
<div>
  <font color='#FF0000'><?php echo $this->mess;?></font>
</div>
<br><br>
<div>
<script>
 function jsOpenComment(_id){
   
    var div = document.getElementById(_id);
     if(div.style.display == 'none') div.style.display = "inline";
      else div.style.display = "none";
 }
</script>
<b>Свадьба</b>
  <form name='fPhotoWed' action="/admin/savewed" method=POST ENCTYPE="multipart/form-data">
    Комментарий к добавляемому фото:<br>
    <textarea name='tComment' rows='3' cols='40'></textarea><br>
    <input type='FILE'  name='file'>
    <input type='submit' value='добавить' name='sAddWed'>
</form>
<br>
 
<table><tr>
<?
   $n = 0;
   
   for( $i = 0;  $i < count( $this->listWed ); $i++){
   
     if( $n == 10 ){print("</tr><tr>"); $n=0;}
    
     print("<td>
               <a href='/admin/photo/?del={$this->listWed[$i]['id']}' style='font-size:10px;'>Удалить</a><br>
               <div style='font-size:10px;cursor:pointer' onClick='jsOpenComment(\"{$this->listWed[$i]['id']}_div\")'><U>Комментарий</U></div>
               <br><img src='".$this->listWed[$i]['link']."' width='70px' height='100px'>
            </td>
            <td valign='bottom'>
              <div id='{$this->listWed[$i]['id']}_div' style='display:none'>
                <form name='fEditComment_{$this->listWed[$i]['id']}' method='POST' action='/admin/commentedit/?ID={$this->listWed[$i]['id']}'>
                 <textarea name='tComment' rows='3' cols='40'>".$this->listWed[$i]['comment']."</textarea><br>
                 <input type='submit' name='sSaveEditComment' value='Save'>
                </form>
              </div>
            </td>
            ");
?>
     
<?php
    $n++; 
    }
?></tr>
</table>

<br>
<br>    
<b>Разное</b>
<form name='fPhotoOther' action="/admin/saveother" method=POST ENCTYPE="multipart/form-data">
    Комментарий к добавляемому фото:<br>
    <textarea name='tComment' rows='3' cols='40'></textarea><br>
    <input type='FILE'  name='file'>
    <input type='submit' value='добавить' name='sAddOther'>
</form>
<br>
<table><tr>
<?
   $n = 0;
   
   for( $i = 0;  $i < count($this->listOther); $i++){
   
     if( $n == 10 ){ print("</tr><tr>"); $n = 0;}
    
     print("<td>
             <a href='/admin/photo/?del={$this->listOther[$i]['id']}' style='font-size:10px;'>Удалить</a><br>
             <div style='font-size:10px;cursor:pointer' onClick='jsOpenComment(\"{$this->listOther[$i]['id']}_div\")'><U>Комментарий</U></div><br>
             <img src='".$this->listOther[$i]['link']."' width='70px' height='100px'>
            </td>
            <td valign='bottom'>
              <div id='{$this->listOther[$i]['id']}_div' style='display:none'>
                <form name='fEditComment_{$this->listOther[$i]['id']}' method='POST' action='/admin/commentedit/?ID={$this->listOther[$i]['id']}'>
                 <textarea name='tComment' rows='3' cols='40'>".$this->listOther[$i]['comment']."</textarea><br>
                 <input type='submit' name='sSaveEditComment' value='Save'>
                </form>
              </div>
            </td>");
?>
     
<?php
    $n++; 
    }
?></tr>
</table>


<br>
<br>    
<b>LoveSory</b>
<form name='fPhotoStory' action="/admin/savestory" method=POST ENCTYPE="multipart/form-data">
    Комментарий к добавляемому фото:<br>
    <textarea name='tComment' rows='3' cols='40'></textarea><br>
    <input type='FILE'  name='file'>
    <input type='submit' value='добавить' name='sAddOther'>
</form>
<br>
<table><tr>
<?
   $n = 0;
   
   for( $i = 0;  $i < count($this->listStory); $i++){
   
     if( $n == 10 ){ print("</tr><tr>"); $n = 0;}
    
     print("<td>
             <a href='/admin/photo/?del={$this->listStory[$i]['id']}' style='font-size:10px;'>Удалить</a><br>
             <div style='font-size:10px;cursor:pointer' onClick='jsOpenComment(\"{$this->listStory[$i]['id']}_div\")'><U>Комментарий</U></div><br>
             <img src='".$this->listStory[$i]['link']."' width='70px' height='100px'></td>
             <td valign='bottom'>
              <div id='{$this->listStory[$i]['id']}_div' style='display:none'>
                <form name='fEditComment_{$this->listStory[$i]['id']}' method='POST' action='/admin/commentedit/?ID={$this->listStory[$i]['id']}'>
                 <textarea name='tComment' rows='3' cols='40'>".$this->listStory[$i]['comment']."</textarea><br>
                 <input type='submit' name='sSaveEditComment' value='Save'>
                </form>
              </div>
            </td>");
?>
     
<?php
    $n++; 
    }
?></tr>
</table>


<br>
<br>    
<b>Детское</b>
<form name='fPhotoCh' action="/admin/savech" method=POST ENCTYPE="multipart/form-data">
    Комментарий к добавляемому фото:<br>
    <textarea name='tComment' rows='3' cols='40'></textarea><br>
    <input type='FILE'  name='file'>
    <input type='submit' value='добавить' name='sAddCh'>
</form>
<br>
<table><tr>
<?
   $n = 0;
   
   for( $i = 0;  $i < count($this->listCh); $i++){
   
     if( $n == 10 ){ print("</tr><tr>"); $n = 0;}
    
     print("<td>
             <a href='/admin/photo/?del={$this->listCh[$i]['id']}' style='font-size:10px;'>Удалить</a><br>
              <div style='font-size:10px;cursor:pointer' onClick='jsOpenComment(\"{$this->listCh[$i]['id']}_div\")'><U>Комментарий</U></div><br>
             <img src='".$this->listCh[$i]['link']."' width='70px' height='100px'>
            </td>
             <td valign='bottom'>
              <div id='{$this->listCh[$i]['id']}_div' style='display:none'>
                <form name='fEditComment_{$this->listCh[$i]['id']}' method='POST' action='/admin/commentedit/?ID={$this->listCh[$i]['id']}'>
                 <textarea name='tComment' rows='3' cols='40'>".$this->listCh[$i]['comment']."</textarea><br>
                 <input type='submit' name='sSaveEditComment' value='Save'>
                </form>
              </div>
            </td>");
?>
     
<?php
    $n++; 
    }
?></tr>
</table>


<br>
<br>    
<b>Выпускные альбомы</b>
<form name='fPhotoFinal' action="/admin/savefinal" method=POST ENCTYPE="multipart/form-data">
 Комментарий к добавляемому фото:<br>
    <textarea name='tComment' rows='3' cols='40'></textarea><br>
    <input type='FILE'  name='file'>
    <input type='submit' value='добавить' name='sAddFinal'>
</form>
<br>
<table><tr>
<?
   $n = 0;
   
   for( $i = 0;  $i < count($this->listFinal); $i++){
   
     if( $n == 10 ){ print("</tr><tr>"); $n = 0;}
    
     print("<td>
             <a href='/admin/photo/?del={$this->listFinal[$i]['id']}' style='font-size:10px;'>Удалить</a><br>
             <div style='font-size:10px;cursor:pointer' onClick='jsOpenComment(\"{$this->listFinal[$i]['id']}_div\")'><U>Комментарий</U></div><br>
             <img src='".$this->listFinal[$i]['link']."' width='70px' height='100px'>
            </td>
            <td valign='bottom'>
              <div id='{$this->listFinal[$i]['id']}_div' style='display:none'>
                <form name='fEditComment_{$this->listFinal[$i]['id']}' method='POST' action='/admin/commentedit/?ID={$this->listFinal[$i]['id']}'>
                 <textarea name='tComment' rows='3' cols='40'>".$this->listFinal[$i]['comment']."</textarea><br>
                 <input type='submit' name='sSaveEditComment' value='Save'>
                </form>
              </div>
            </td>");
?>
     
<?php
    $n++; 
    }
?></tr>
</table>

</div>
</body>
</html>  